import Head from "next/head"


const Page = ({children}) => {
    return (
        <>
        <Head>
        <title>Overstars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      </>
    )
}
export default Page